export const siteMeta = {
	name: 'AI Prompt Gear',
	shortName: 'AI Prompt Gear',
	editorialTeamName: 'AI Prompt Gear Editorial Desk',
	reviewDeskName: 'AI Prompt Gear Review Desk',
	domain: 'aipromptgear.com',
	siteUrl: 'https://aipromptgear.com',
	description:
		'Reference system for production prompting, agent workflows, model routing, team operations, and evaluation.',
	tagline:
		'Production prompting, agent operations, and model decisions organized for reusable systems instead of one-off hacks.',
	email: 'cqq365@gmail.com',
	languageTag: 'en-US',
	ogLocale: 'en_US',
	themeColor: '#188d88',
	backgroundColor: '#eef9f8',
	faviconPath: '/favicon.svg',
	ogImagePath: '/social-card.png',
	ogImageAlt:
		'AI Prompt Gear social share card for production prompting, agent workflows, and model decisions.',
	icon192Path: '/icon-192.png',
	icon512Path: '/icon-512.png',
	appleTouchIconPath: '/apple-touch-icon.png',
	repoUrl: 'https://github.com/cocmo1024/aipromptgear.com',
	xUrl: 'https://x.com/oocxx_com',
	sameAs: ['https://x.com/oocxx_com'],
	editorialMethodSummary:
		'Pages are built from official platform documentation, pricing pages, product release notes, and editorial analysis focused on production AI system decisions.',
	indexNowKey: '393db214-c90a-4453-b07d-4af42a7e2c5f',
	publishingPrinciplesPath: '/editorial-policy/',
	richResultImages: [
		{
			path: '/social-card.png',
			width: 1200,
			height: 630,
			alt: 'AI Prompt Gear social share card for production prompting, agent workflows, and model decisions.',
		},
		{
			path: '/search-preview-4x3.svg',
			width: 1200,
			height: 900,
			alt: 'AI Prompt Gear reference map for prompting systems, agent workflows, and evaluation.',
		},
		{
			path: '/search-preview-1x1.svg',
			width: 1200,
			height: 1200,
			alt: 'AI Prompt Gear square preview for production prompting and agent operations.',
		},
	],
	editorialEntities: {
		'editorial-desk': {
			name: 'AI Prompt Gear Editorial Desk',
			path: '/editorial-desk/',
			description:
				'Maintains reference pages on agent workflows, model decisions, prompt operations, and AI product economics.',
			expertise: [
				'production prompting',
				'agent systems',
				'eval operations',
				'AI platform economics',
			],
		},
		'review-desk': {
			name: 'AI Prompt Gear Review Desk',
			path: '/review-desk/',
			description:
				'Reviews major pages for technical coherence, pricing accuracy, governance claims, and production applicability.',
			expertise: [
				'technical review',
				'pricing checks',
				'governance controls',
				'agent rollout risk',
			],
		},
	},
	keywords: [
		'ai prompting',
		'AI prompt library',
		'copy prompts',
		'gpt-image-2 prompts',
		'image prompt patterns',
		'image generation prompts',
		'agent workflows',
		'model routing',
		'prompt operations',
		'AI evaluation',
	],
	sectionLabels: {
		'use-cases': 'Team Scenarios',
		clusters: 'Topic Clusters',
		'market-signals': 'Market Signals',
		workflows: 'Workflows',
		'agent-systems': 'Agent Systems',
		'prompt-library': 'Prompt Library',
		'models-and-apis': 'Models and APIs',
		tooling: 'Tooling',
		'tool-comparisons': 'Tool Comparisons',
		evaluation: 'Evaluation',
	},
};
