export const siteMeta = {
	name: 'AI Prompt Gear',
	shortName: 'AI Prompt Gear',
	editorialTeamName: 'AI Prompt Gear Editorial Desk',
	reviewDeskName: 'AI Prompt Gear Review Desk',
	domain: 'aipromptgear.com',
	siteUrl: 'https://aipromptgear.com',
	description:
		'Reference system for production prompting, agent workflows, model routing, team operations, and evaluation.',
	tagline:
		'Production prompting, agent operations, and model decisions organized for reusable systems instead of one-off hacks.',
	email: 'cqq365@gmail.com',
	languageTag: 'en-US',
	ogLocale: 'en_US',
	themeColor: '#188d88',
	backgroundColor: '#eef9f8',
	faviconPath: '/favicon.svg',
	ogImagePath: '/social-card.png',
	ogImageAlt:
		'AI Prompt Gear social share card for production prompting, agent workflows, and model decisions.',
	icon192Path: '/icon-192.png',
	icon512Path: '/icon-512.png',
	appleTouchIconPath: '/apple-touch-icon.png',
	repoUrl: 'https://github.com/cocmo1024/aipromptgear.com',
	xUrl: 'https://x.com/oocxx_com',
	sameAs: ['https://x.com/oocxx_com'],
	editorialMethodSummary:
		'Pages are built from official platform documentation, pricing pages, product release notes, and editorial analysis focused on production AI system decisions.',
	indexNowKey: '393db214-c90a-4453-b07d-4af42a7e2c5f',
	publishingPrinciplesPath: '/editorial-policy/',
	richResultImages: [
		{
			path: '/search-previews/default-16x9.webp',
			width: 1200,
			height: 675,
			alt: 'Abstract AI workflow map for production prompting, agent workflows, and model decisions.',
		},
		{
			path: '/search-previews/default-4x3.webp',
			width: 1200,
			height: 900,
			alt: 'Abstract AI workflow map for production prompting, agent workflows, and model decisions.',
		},
		{
			path: '/search-previews/default-1x1.webp',
			width: 1200,
			height: 1200,
			alt: 'Abstract AI workflow map for production prompting, agent workflows, and model decisions.',
		},
	],
	richResultImageAliases: {
		'ai-cost-and-compute': 'models-and-apis',
		coding: 'agent-systems',
		'coding-agents': 'agent-systems',
		'deep-research': 'use-cases',
		evalops: 'evaluation',
		'enterprise-agent-platforms': 'tool-comparisons',
		'mcp-security': 'agent-systems',
		'openai-codex-desktop': 'tool-comparisons',
		'site-foundation': 'clusters',
		'site-policy': 'clusters',
		'support-ai': 'use-cases',
	},
	richResultImageSets: {
		default: [
			{
				path: '/search-previews/default-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Abstract AI workflow map for production prompting, agent workflows, and model decisions.',
			},
			{
				path: '/search-previews/default-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Abstract AI workflow map for production prompting, agent workflows, and model decisions.',
			},
			{
				path: '/search-previews/default-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Abstract AI workflow map for production prompting, agent workflows, and model decisions.',
			},
		],
		'agent-systems': [
			{
				path: '/search-previews/agent-systems-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Agent runtime diagram with connected tools, permissions, and review gates.',
			},
			{
				path: '/search-previews/agent-systems-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Agent runtime diagram with connected tools, permissions, and review gates.',
			},
			{
				path: '/search-previews/agent-systems-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Agent runtime diagram with connected tools, permissions, and review gates.',
			},
		],
		clusters: [
			{
				path: '/search-previews/clusters-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Topic cluster map with connected AI operations reference nodes.',
			},
			{
				path: '/search-previews/clusters-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Topic cluster map with connected AI operations reference nodes.',
			},
			{
				path: '/search-previews/clusters-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Topic cluster map with connected AI operations reference nodes.',
			},
		],
		evaluation: [
			{
				path: '/search-previews/evaluation-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Evaluation scorecard dashboard with trace checks and release gates.',
			},
			{
				path: '/search-previews/evaluation-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Evaluation scorecard dashboard with trace checks and release gates.',
			},
			{
				path: '/search-previews/evaluation-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Evaluation scorecard dashboard with trace checks and release gates.',
			},
		],
		'image-prompts': [
			{
				path: '/search-previews/image-prompts-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Creative image prompt board with frames, reference panels, and comparison marks.',
			},
			{
				path: '/search-previews/image-prompts-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Creative image prompt board with frames, reference panels, and comparison marks.',
			},
			{
				path: '/search-previews/image-prompts-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Creative image prompt board with frames, reference panels, and comparison marks.',
			},
		],
		'market-signals': [
			{
				path: '/search-previews/market-signals-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'AI market signal radar with trend arcs and decision nodes.',
			},
			{
				path: '/search-previews/market-signals-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'AI market signal radar with trend arcs and decision nodes.',
			},
			{
				path: '/search-previews/market-signals-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'AI market signal radar with trend arcs and decision nodes.',
			},
		],
		'models-and-apis': [
			{
				path: '/search-previews/models-and-apis-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Model routing and API cost lane diagram for production AI systems.',
			},
			{
				path: '/search-previews/models-and-apis-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Model routing and API cost lane diagram for production AI systems.',
			},
			{
				path: '/search-previews/models-and-apis-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Model routing and API cost lane diagram for production AI systems.',
			},
		],
		'prompt-library': [
			{
				path: '/search-previews/prompt-library-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Prompt library cards with versioned templates and quality checks.',
			},
			{
				path: '/search-previews/prompt-library-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Prompt library cards with versioned templates and quality checks.',
			},
			{
				path: '/search-previews/prompt-library-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Prompt library cards with versioned templates and quality checks.',
			},
		],
		prompts: [
			{
				path: '/search-previews/prompts-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Prompt radar board with signal cards, ranking marks, and reusable templates.',
			},
			{
				path: '/search-previews/prompts-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Prompt radar board with signal cards, ranking marks, and reusable templates.',
			},
			{
				path: '/search-previews/prompts-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Prompt radar board with signal cards, ranking marks, and reusable templates.',
			},
		],
		'tool-comparisons': [
			{
				path: '/search-previews/tool-comparisons-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'AI tool comparison matrix with decision columns and evidence checks.',
			},
			{
				path: '/search-previews/tool-comparisons-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'AI tool comparison matrix with decision columns and evidence checks.',
			},
			{
				path: '/search-previews/tool-comparisons-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'AI tool comparison matrix with decision columns and evidence checks.',
			},
		],
		tooling: [
			{
				path: '/search-previews/tooling-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'AI operations tooling control panel with logs, alerts, and governance checks.',
			},
			{
				path: '/search-previews/tooling-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'AI operations tooling control panel with logs, alerts, and governance checks.',
			},
			{
				path: '/search-previews/tooling-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'AI operations tooling control panel with logs, alerts, and governance checks.',
			},
		],
		'use-cases': [
			{
				path: '/search-previews/use-cases-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'AI use case rollout board with teams, workflows, approvals, and outcome metrics.',
			},
			{
				path: '/search-previews/use-cases-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'AI use case rollout board with teams, workflows, approvals, and outcome metrics.',
			},
			{
				path: '/search-previews/use-cases-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'AI use case rollout board with teams, workflows, approvals, and outcome metrics.',
			},
		],
		workflows: [
			{
				path: '/search-previews/workflows-16x9.webp',
				width: 1200,
				height: 675,
				alt: 'Workflow routing board with handoffs, review gates, and automation steps.',
			},
			{
				path: '/search-previews/workflows-4x3.webp',
				width: 1200,
				height: 900,
				alt: 'Workflow routing board with handoffs, review gates, and automation steps.',
			},
			{
				path: '/search-previews/workflows-1x1.webp',
				width: 1200,
				height: 1200,
				alt: 'Workflow routing board with handoffs, review gates, and automation steps.',
			},
		],
	},
	editorialEntities: {
		'editorial-desk': {
			name: 'AI Prompt Gear Editorial Desk',
			path: '/editorial-desk/',
			description:
				'Maintains reference pages on agent workflows, model decisions, prompt operations, and AI product economics.',
			expertise: [
				'production prompting',
				'agent systems',
				'eval operations',
				'AI platform economics',
			],
		},
		'review-desk': {
			name: 'AI Prompt Gear Review Desk',
			path: '/review-desk/',
			description:
				'Reviews major pages for technical coherence, pricing accuracy, governance claims, and production applicability.',
			expertise: [
				'technical review',
				'pricing checks',
				'governance controls',
				'agent rollout risk',
			],
		},
	},
	keywords: [
		'ai prompting',
		'AI prompt radar',
		'AI prompt library',
		'copy prompts',
		'trending AI prompts',
		'gpt-image-2 prompts',
		'image prompt patterns',
		'image generation prompts',
		'agent workflows',
		'model routing',
		'prompt operations',
		'AI evaluation',
	],
	sectionLabels: {
		'use-cases': 'Team Scenarios',
		clusters: 'Topic Clusters',
		'market-signals': 'Market Signals',
		workflows: 'Workflows',
		'agent-systems': 'Agent Systems',
		prompts: 'Prompt Radar',
		'prompt-library': 'Prompt Library',
		'models-and-apis': 'Models and APIs',
		tooling: 'Tooling',
		'tool-comparisons': 'Tool Comparisons',
		evaluation: 'Evaluation',
	},
};
